# TOML Ref: https://github.com/toml-lang/toml
# Example: https://raw.githubusercontent.com/greshake/i3status-rust/master/examples/config.toml
# Block Doc: https://greshake.github.io/i3status-rust/i3status_rs/blocks/index.html
# Repo: https://github.com/greshake/i3status-rust

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome5"

#[[block]]
#block = "weather"
#format = "$weather ($location) $temp, $wind m/s $direction"
#[block.service]
#name = "openweathermap"
#lang = "en"
##api_key = "{{ pass "OPENWEATHER_API_KEY" }}"
#city_id = "3413829" # Reykjavík
## city_id = "1267995" # Kanpur
#units = "metric"
#
#[[block]]
#block = "weather"
#format = "IISERM $weather $temp"
#[block.service]
#name = "openweathermap"
#lang = "en"
##api_key = "{{ pass "OPENWEATHER_API_KEY" }}"
#units = "metric"
#coordinates = ["30.66361594277602","76.72912558319638"] # IISER-M
## coordinates = ["64.140461", "-21.961226"] # Reykjavik
## coordinates = ["26.512530794602895", "80.2330716579492"] # IITK


[[block]]
block = "time"
format = "SYD:$timestamp.datetime(f:'%R') "
timezone = "Australia/Sydney"
interval = 60

[[block]]
block = "time"
format = "ADL:$timestamp.datetime(f:'%R') "
timezone = "Australia/Adelaide"
interval = 60

[[block]]
block = "time"
format = "KL:$timestamp.datetime(f:'%R') "
timezone = "Asia/Singapore"
interval = 60

[[block]]
block = "time"
format = "EU:$timestamp.datetime(f:'%R') "
timezone = "Europe/Stockholm"
interval = 60

[[block]]
block = "time"
format = "UK:$timestamp.datetime(f:'%R') "
timezone = "GB"
interval = 60

[[block]]
block = "time"
format = "NY:$timestamp.datetime(f:'%R') "
timezone = "America/New_York"
interval = 60


[[block]]
block = "time"
format = "SF:$timestamp.datetime(f:'%R') "
timezone = "America/Los_Angeles"
interval = 60



[[block]]
block = "battery"
interval = 10
info = 50 
good = 85
warning = 30
critical = 15
#format = "$percentage $time $power|N/A"
format = " $icon $percentage $power |N/A"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20,rot_interval:0.5) $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]

# Emacs Stuff (cross platform)
# Local Variables:
# mode: conf-toml-mode
# End:
