# TOML Ref: https://github.com/toml-lang/toml
# Example: https://raw.githubusercontent.com/greshake/i3status-rust/master/examples/config.toml
# Block Doc: https://greshake.github.io/i3status-rust/i3status_rs/blocks/index.html
# Repo: https://github.com/greshake/i3status-rust

[theme]
theme = "solarized-dark"
[icons]
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
alert_unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_used_percents.eng(w:2) "

[[block]]
block = "cpu"
interval = 1
format = " $icon$utilization "
format_alt = " $icon $barchart $utilization "

[[block]]
block = "load"
interval = 2
#format = "$icon$1m"

[[block]]
block = "net"
device = "wlp1s0"
interval = 1
missing_format = " ^icon_net_wireless ^icon_net_down  Down "
format_alt = " $icon {$signal_strength $ssid$frequency $bitrate|Wired connection} $ip "
format = " $icon ^icon_net_down $speed_down.eng(prefix:K,u:b) ^icon_net_up $speed_up.eng(prefix:K,u:b) "


[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 60
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d %b %R') "
#full = " $icon $timestamp.datetime(f:'%a %R') "
# full = " $icon $timestamp.datetime(f:'%a %R %Z') "
#short = " $icon $timestamp.datetime(f:%R) "
